name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v2
        with:
          github_user_name: yoshii001  # Replace with your GitHub username
          output: dist/github-contribution-grid-snake.svg

      - name: Upload the snake to the repository
        run: |
          mkdir -p resources/img
          mv dist/github-contribution-grid-snake.svg resources/img/github-contribution-grid-snake.svg
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add resources/img/github-contribution-grid-snake.svg
          git commit -m "Generated snake animation"
          git push
